### ISSUE TITLE
red coin

### ISSUE THREAD

**Issue by bearwaresmm** [Thermo-Dyn/Super-Minecraft-Maker#1]
Some issues with red coins
- sometimes the red coin count doesn't reset properly
- sometimes collecting 8 red coins and getting a key doesn't remove the coins from your inventory
- dying on top of where a red coin is will make you instantly collect the coin before even spawning
- collectables can respawn when they're not supposed to if the instant respawn gamerule is enabled
- sfx attached to red coins still play where they were even after being collected

[maro.zip](https://github.com/Thermo-Dyn/Super-Minecraft-Maker/files/12561881/maro.zip)

**Comment by Thermo-Dyn** [comment]
I think i fixed it all
